gstreamer1.0-plugins-base: Add Upstream-Status: field
It fixes the following error:

  ERROR: gstreamer1.0-plugins-base-1.22.12-r0 do_patch: QA Issue: Missing Upstream-Status in patch

No need to set the following workaround in conf/local.conf

  ERROR_QA:remove:pn-gstreamer1.0-plugins-base = "patch-status"
  WARN_QA:append:pn-gstreamer1.0-plugins-base = " patch-status"

Signed-off-by: Kentaro Hayashi <hayashi@clear-code.com>